### ISSUE TITLE
Create script to convert GeoNames data set into transliteration-pair data

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/interoperable-transliteration#41]
GeoNames data is a great source of transliteration testing.

For each GeoNames data set per country, we only need:
* Column S "LC" is the language.
* Column W "FULL_NAME_RO". The name of the place.
* Column C "UNI". The unique identifier of this row.
* Column AF "NAME_LINK". This column is used to associate two rows by finding the same value in "UNI"
* Column AG "TRANSL_CD". The system used to transliterate this row.
* Column U "GENERIC". The "type" of this place, which is necessary in transliteration. (e.g. "Queen's Road" will have "GENERIC" as "Road", so It doesn't affect transliteration)

Given this example:
<img width="1961" alt="Screen Shot 2020-01-08 at 1 08 13 AM" src="https://user-images.githubusercontent.com/11865/71913873-5ac52d00-31b3-11ea-8d08-11dbabdd1c51.png">

We want to convert it into this format:

```yaml
- lang: zho
  source:
    full_name: 徐宸溪
    generic: 溪
  destination:
    full_name: Xuchen Xi
    generic: Xi
  translit_system: zho_Hani2Latn_GCH_1979
```

We need a script that processes these.

Example: Bulgaria contains Cyrillic names
[bu.txt.zip](https://github.com/riboseinc/interoperable-transliteration/files/4031611/bu.txt.zip)

Ping @abunashir this is rather urgent for this week/weekend. Thanks!
